""" spectcl_codebreaker_ui.py --

 UI generated by GUI Builder Build 146 on 2014-09-18 03:50:02 from:
    C:/Users/Public/projects/python_codebreaker/codebreaker/project/02_guibuilder/codebreaker08_spectcl/spectcl_codebreaker.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Spectcl_codebreaker(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._label_1 = Tkinter.Label(root,
            font = "{MS Sans Serif} 20",
            text = "CodeBreaker",
        )
        self._button_1 = Tkinter.Button(root,
            text = "Guess",
        )
        self._label_2 = Tkinter.Label(root,
            text = "Enter Your 4-digit Guess here:",
        )
        self._button_2 = Tkinter.Button(root,
            text = "New Game",
        )
        self._button_3 = Tkinter.Button(root,
            text = "About",
        )
        self._button_4 = Tkinter.Button(root,
            text = "Exit",
        )
        self._entry_1 = Tkinter.Entry(root,
            width = 0,
        )
        self._label_3 = Tkinter.Label(root,
            text = "Result:",
        )
        self._listbox_1 = Tkinter.Listbox(root,
            height = 7,
            width = 0,
        )
        self._scrollbar_1 = Tkinter.Scrollbar(root,
            takefocus = 1,
        )
        self.menu = Tkinter.Menu(root,
        )

        # widget commands

        self._button_1.configure(
            command = self._button_1_command
        )
        self._button_2.configure(
            command = self._button_2_command
        )
        self._button_3.configure(
            command = self._button_3_command
        )
        self._button_4.configure(
            command = self._button_4_command
        )
        self._entry_1.configure(
            invalidcommand = self._entry_1_invalidcommand
        )
        self._entry_1.configure(
            validatecommand = self._entry_1_validatecommand
        )
        self._entry_1.configure(
            xscrollcommand = self._entry_1_xscrollcommand
        )
        self._listbox_1.configure(
            xscrollcommand = self._scrollbar_1.set
        )
        self._listbox_1.configure(
            yscrollcommand = self._listbox_1_yscrollcommand
        )
        self._scrollbar_1.configure(
            command = self._listbox_1.yview
        )
        self.menuitem1 = Tkinter.Menu(self.menu,
            tearoff = 0,
        )
        self.menu.add_cascade(
            label = "File",
            menu = self.menuitem1,
        )
        self.menuitem2 = Tkinter.Menu(self.menu,
            tearoff = 0,
        )
        self.menu.add_cascade(
            label = "Play",
            menu = self.menuitem2,
        )
        self.menuitem1.add_command(
            command = self._exit_command,
            label = "Exit",
        )
        self.menuitem1.add_command(
            command = self._about_command,
            label = "About",
        )
        self.menuitem2.add_command(
            command = self._new_game_command,
            label = "New Game",
        )
        self.menuitem2.add_command(
            command = self._new_ud_game_command,
            label = "New Game with user-defined Secret Number",
        )
        self.menuitem2.add_command(
            command = self._hint_command,
            label = "Hint",
        )
        self.menuitem2.add_command(
            command = self._guess_command,
            label = "Guess",
        )


        # Geometry Management
        self._label_1.grid(
            in_    = root,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_1.grid(
            in_    = root,
            column = 4,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_2.grid(
            in_    = root,
            column = 2,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_2.grid(
            in_    = root,
            column = 4,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_3.grid(
            in_    = root,
            column = 4,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_4.grid(
            in_    = root,
            column = 4,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._entry_1.grid(
            in_    = root,
            column = 2,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ew"
        )
        self._label_3.grid(
            in_    = root,
            column = 2,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._listbox_1.grid(
            in_    = root,
            column = 2,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._scrollbar_1.grid(
            in_    = root,
            column = 3,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ns"
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 69, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 79, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 63, pad = 0)
        root.grid_rowconfigure(4, weight = 0, minsize = 73, pad = 0)
        root.grid_rowconfigure(5, weight = 1, minsize = 131, pad = 0)
        root.grid_rowconfigure(6, weight = 0, minsize = 43, pad = 0)
        root.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 237, pad = 0)
        root.grid_columnconfigure(3, weight = 0, minsize = 32, pad = 0)
        root.grid_columnconfigure(4, weight = 0, minsize = 253, pad = 0)
        root.configure(menu = self.menu)


