""" spectcl_helloworld_ui.py --

 UI generated by GUI Builder Build 146 on 2014-09-10 08:32:25 from:
    C:/Users/Public/projects/python_codebreaker/codebreaker/project/02_guibuilder/codebreaker08_spectcl/spectcl_helloworld.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Spectcl_helloworld(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization


        # Geometry Management


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)


