""" spectcl_helloworld.py --

 UI generated by GUI Builder Build 146 on 2014-09-10 08:32:25 from:
    C:/Users/Public/projects/python_codebreaker/codebreaker/project/02_guibuilder/codebreaker08_spectcl/spectcl_helloworld.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from Tkinter import *
from spectcl_helloworld_ui import Spectcl_helloworld

# BEGIN USER CODE global

# END USER CODE global

class CustomSpectcl_helloworld(Spectcl_helloworld):
    pass

    # BEGIN CALLBACK CODE
    # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

    # END CALLBACK CODE

    # BEGIN USER CODE class

    # END USER CODE class

def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    try: userinit()
    except NameError: pass
    root = Tk()
    demo = CustomSpectcl_helloworld(root)
    root.title('spectcl_helloworld')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
