# spectcl_secretnumber_ui.tcl --
#
# UI generated by GUI Builder Build 146 on 2015-09-15 07:15:37 from:
#    C:/Users/Public/archive/github/tcl-codebreaker/project_spectcl/spectcl_secretnumber.ui
# THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
# The associated callback file should be modified instead.
#

# Declare the namespace for this dialog
namespace eval spectcl_secretnumber {}

package require Tk
# spectcl_secretnumber::ui --
#
#   Create the UI for this dialog.
#
# ARGS:
#   root     the parent window for this form
#   args     a catch-all for other args, but none are expected
#
proc spectcl_secretnumber::ui {root args} {
    # this handles '.' as a special case
    set base [expr {($root == ".") ? "" : $root}]
    variable ROOT $root
    variable BASE $base
    variable SCRIPTDIR ; # defined in main script


    # Widget Initialization
    variable _label_1 [label $BASE._label_1 \
	    -text "Enter Text"]
    variable _button_1 [button $BASE._button_1 \
	    -command [namespace code [list _button_1_command]] \
	    -text "Clear"]
    variable _entry_1 [entry $BASE._entry_1 \
	    -invalidcommand [namespace code [list _entry_1_invalidcommand]] \
	    -validatecommand [namespace code [list _entry_1_validatecommand]] \
	    -width 0 \
	    -xscrollcommand [namespace code [list _entry_1_xscrollcommand]]]


    # Geometry Management

    grid $BASE._label_1 -in $root -row 1 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE._button_1 -in $root -row 2 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE._entry_1 -in $root -row 1 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "ew"

    # Resize Behavior
    grid rowconfigure $root 1 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $root 2 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 1 -weight 0 -minsize 138 -pad 0
    grid columnconfigure $root 2 -weight 0 -minsize 244 -pad 0
}
