#package provide CodeBreaker 1.0

# spectcl_codebreaker_ui.tcl --
#
# UI generated by GUI Builder Build 146 on 2015-09-15 18:55:13 from:
#    C:/Users/Public/archive/github/codebreaker/projects/tcl/spectcl/spectcl_codebreaker.ui
# THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
# The associated callback file should be modified instead.
#

# Declare the namespace for this dialog
namespace eval spectcl_codebreaker {}

package require Tk
# spectcl_codebreaker::ui --
#
#   Create the UI for this dialog.
#
# ARGS:
#   root     the parent window for this form
#   args     a catch-all for other args, but none are expected
#
proc spectcl_codebreaker::ui {root args} {
    # this handles '.' as a special case
    set base [expr {($root == ".") ? "" : $root}]
    variable ROOT $root
    variable BASE $base
    variable SCRIPTDIR ; # defined in main script


    # Widget Initialization
    variable _label_1 [label $BASE._label_1 \
	    -font {{MS Sans Serif} 20} \
	    -text "CodeBreaker"]
    variable _button_1 [button $BASE._button_1 \
	    -command [namespace code [list button1Cmd_command]] \
	    -text "Guess"]
    variable _label_2 [label $BASE._label_2 \
	    -text "Enter Your 4-digit Guess here:"]
    variable _button_2 [button $BASE._button_2 \
	    -command [namespace code [list button2Cmd_command]] \
	    -text "New Game"]
    variable _button_3 [button $BASE._button_3 \
	    -command [namespace code [list button3Cmd_command]] \
	    -text "About"]
    variable _button_4 [button $BASE._button_4 \
	    -command [namespace code [list button4Cmd_command]] \
	    -text "Exit"]
    variable _entry_1 [entry $BASE._entry_1 \
	    -invalidcommand [namespace code [list _entry_1_invalidcommand]] \
	    -validatecommand [namespace code [list _entry_1_validatecommand]] \
	    -width 0 \
	    -xscrollcommand [namespace code [list _entry_1_xscrollcommand]]]
    variable _label_3 [label $BASE._label_3 \
	    -text "Result:"]
    variable _listbox_1 [listbox $BASE._listbox_1 \
	    -height 7 \
	    -width 0 \
	    -yscrollcommand [namespace code [list _listbox_1_yscrollcommand]]]
    #-xscrollcommand "_scrollbar_1.set"
    variable _scrollbar_1 [scrollbar $BASE._scrollbar_1 \
	    -command "_listbox_1.yview" \
	    -takefocus 1]
    variable menu [menu $BASE.menu]
    variable menuitem1 [menu $BASE.menuitem1 \
	    -tearoff 0]
    $BASE.menu add cascade \
	    -label "File" \
	    -menu $BASE.menuitem1
    variable menuitem2 [menu $BASE.menuitem2 \
	    -tearoff 0]
    $BASE.menu add cascade \
	    -label "Play" \
	    -menu $BASE.menuitem2
    $BASE.menuitem1 add command \
	    -command "spectcl_codebreaker::exitCmd" \
	    -label "Exit"
    $BASE.menuitem1 add command \
	    -command "spectcl_codebreaker::aboutCmd" \
	    -label "About"
    $BASE.menuitem2 add command \
	    -command "spectcl_codebreaker::newGameCmd" \
	    -label "New Game"
    $BASE.menuitem2 add command \
	    -command "spectcl_codebreaker::newSelfdefinedGame" \
	    -label "New Game with user-defined Secret Number"
    $BASE.menuitem2 add command \
	    -command "spectcl_codebreaker::hintCmd" \
	    -label "Hint"
    $BASE.menuitem2 add command \
	    -command "spectcl_codebreaker::guessCmd" \
	    -label "Guess"


    # Geometry Management

    grid $BASE._label_1 -in $root -row 1 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE._button_1 -in $root -row 2 -column 4 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE._label_2 -in $root -row 2 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE._button_2 -in $root -row 3 -column 4 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE._button_3 -in $root -row 4 -column 4 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE._button_4 -in $root -row 5 -column 4 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE._entry_1 -in $root -row 3 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "ew"
    grid $BASE._label_3 -in $root -row 4 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE._listbox_1 -in $root -row 5 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "news"
    grid $BASE._scrollbar_1 -in $root -row 5 -column 3 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "ns"

    # Resize Behavior
    grid rowconfigure $root 1 -weight 0 -minsize 69 -pad 0
    grid rowconfigure $root 2 -weight 0 -minsize 79 -pad 0
    grid rowconfigure $root 3 -weight 0 -minsize 63 -pad 0
    grid rowconfigure $root 4 -weight 0 -minsize 73 -pad 0
    grid rowconfigure $root 5 -weight 1 -minsize 131 -pad 0
    grid rowconfigure $root 6 -weight 0 -minsize 43 -pad 0
    grid columnconfigure $root 1 -weight 1 -minsize 40 -pad 0
    grid columnconfigure $root 2 -weight 0 -minsize 237 -pad 0
    grid columnconfigure $root 3 -weight 0 -minsize 32 -pad 0
    grid columnconfigure $root 4 -weight 0 -minsize 253 -pad 0
    $ROOT configure -menu $BASE.menu
}
