# spectcl_secretnumber.tcl --
#
# UI generated by GUI Builder Build 146 on 2015-09-15 07:15:37 from:
#    C:/Users/Public/archive/github/tcl-codebreaker/project_spectcl/spectcl_secretnumber.ui
# This file is auto-generated.  Only the code within
#    '# BEGIN USER CODE'
#    '# END USER CODE'
# and code inside the callback subroutines will be round-tripped.
# The proc names 'ui' and 'init' are reserved.
#

package require Tk 8.4

# Declare the namespace for this dialog
namespace eval spectcl_secretnumber {}

# Source the ui file, which must exist
set spectcl_secretnumber::SCRIPTDIR [file dirname [info script]]
source [file join $spectcl_secretnumber::SCRIPTDIR spectcl_secretnumber_ui.tcl]

# BEGIN USER CODE

# END USER CODE

# BEGIN CALLBACK CODE
# ONLY EDIT CODE INSIDE THE PROCS.

# spectcl_secretnumber::_button_1_command --
#
# Callback to handle _button_1 widget option -command
#
# ARGS:
#    <NONE>
#
proc spectcl_secretnumber::_button_1_command args {}

# spectcl_secretnumber::_entry_1_invalidcommand --
#
# Callback to handle _entry_1 widget option -invalidcommand
#
# ARGS:
#    <NONE>
#
proc spectcl_secretnumber::_entry_1_invalidcommand args {}

# spectcl_secretnumber::_entry_1_validatecommand --
#
# Callback to handle _entry_1 widget option -validatecommand
#
# ARGS:
#    <NONE>
#
proc spectcl_secretnumber::_entry_1_validatecommand args {}

# spectcl_secretnumber::_entry_1_xscrollcommand --
#
# Callback to handle _entry_1 widget option -xscrollcommand
#
# ARGS:
#    <NONE>
#
proc spectcl_secretnumber::_entry_1_xscrollcommand args {}

# END CALLBACK CODE

# spectcl_secretnumber::init --
#
#   Call the optional userinit and initialize the dialog.
#   DO NOT EDIT THIS PROCEDURE.
#
# Arguments:
#   root   the root window to load this dialog into
#
# Results:
#   dialog will be created, or a background error will be thrown
#
proc spectcl_secretnumber::init {root args} {
    # Catch this in case the user didn't define it
    catch {spectcl_secretnumber::userinit}
    if {[info exists embed_args]} {
	# we are running in the plugin
	spectcl_secretnumber::ui $root
    } elseif {$::argv0 == [info script]} {
	# we are running in stand-alone mode
	wm title $root spectcl_secretnumber
	if {[catch {
	    # Create the UI
	    spectcl_secretnumber::ui  $root
	} err]} {
	    bgerror $err ; exit 1
	}
    }
    catch {spectcl_secretnumber::run $root}
}
spectcl_secretnumber::init .

